### ISSUE TITLE
Problem with enableCellAutosizing

### ISSUE THREAD

**Issue by MarkoTukiainen** [nimmneun/onesheet#35]
I found an issue that caused all the columns that had data to be effectively displayed as 0 width when turning enableCellAutosizing on. This might be related to my system locale or something similar. The $cellWidth that the sizeCalculator->getCellWidth was returning turned out to be a number with a comma as the decimal separator, such as "2,142". 

I fixed the problem with a bit of a hack, by changing
```$this->columnWidths[$cellIndex] = $cellWidth;```

to
```$this->columnWidths[$cellIndex] = str_replace(',', '.', $cellWidth);```

in the updateColumnWidths method of Sheet.php. I'm sure there's a better way to do it, though.

**Comment by nimmneun** [comment]
Nice spot =) Since it's excel/spreadsheetml format which doesn't understand the commas as decimal point in the cols xml tag, the logic has been applied to the actual generation of the xml string. Thanks for reporting the issue =)
