### ISSUE TITLE
OfficeImportErrorDomain when downloading file on iOS

### ISSUE THREAD

**Issue by snapeuh** [nimmneun/onesheet#48]
Hello,

We use OneSheet to generate exports in our app since a week or two (we were generating CSVs before). Lately our iOS users reported that an error was shown instead of the downloaded export : "OfficeImportErrorDomain".

I investigated and ended up in a Box/Spout issue : https://github.com/box/spout/issues/85 with a MR that was solving the problem.

So I tested on OneSheet and it's working fine too. So I am submitting an MR to OneSheet to solve this problem.

Thanks for your work,

Romain.

**Comment by nimmneun** [comment]
thank for your contribution @snapeuh appreciate it 👍
