### ISSUE TITLE
New lines not working

### ISSUE THREAD

**Issue by Feloot** [nimmneun/onesheet#51]
Hello,

I'm trying to output new lines in a cell. I've tried with \n, \r\n and PHP_EOL but none of them works, unless I give focus to the cell on Microsoft Excel and then validate it again, and in that case the new line will appear.

For instance : 
`
$onesheet = new \OneSheet\Writer();
$onesheet->enableCellAutosizing();
$onesheet->addRow(["Apple \n Orange"]);
$onesheet->writeToFile('sheet.xlsx');
`

... will just output "Apple Orange" on the same line.

I'm not sure if this is an Excel settings issue or if it's OneSheet not formatting new lines correctly...

Any advice?

Thanks

**Comment by nimmneun** [comment]
Hi @Feloot,

sorry to disappoint you there, but the library currently does not support content type formatting for cells and it is not planned to add it.
The only formats it knows are inlineStr, boolean and numbers.

phpoffice/spreadsheet supports this though (see sample code linked below), which might be an option for you:
https://github.com/PHPOffice/PhpSpreadsheet/blob/a7986520f999c4e4dad17c59ae07b8549079456a/samples/Basic/01_Simple.php#L42

**Comment by Feloot** [comment]
Hi @nimmneun,

Thank you for your reply. I'll have a look at phpoffice/spreadsheet.

Thanks !
