### ISSUE TITLE
Write multiple sheets

### ISSUE THREAD

**Issue by nimmneun** [nimmneun/onesheet#53]
In some cases, it would be helpful to be able to write multiple sheets. E.g. if the finance team wants to have a list of order_items and refund_items in one file for a YoY comparison/evaluation of sold products vs their refund quota.

- [x] try to make this a non-breaking change (aim for v1.2 over v2.0)
- [x] ensure auto-sizing feature works for individual sheets
- [x] ensure repeatable print ranges work for individual sheets
- [x] ensure tests for single and multiple sheets are added

**Comment by shacerteo** [comment]
thanks =)
