### ISSUE TITLE
Create empty file

### ISSUE THREAD

**Issue by dehuk** [nimmneun/onesheet#57]
Hi,

When I am trying to create a file without any lines I get a broken file. Is it possible to create an empty file?

`
$onesheet = new \OneSheet\Writer('/optional/fonts/directory');
$onesheet->writeToFile('hello_world.xlsx');
`

<img width="259" alt="Screenshot 2021-07-16 at 11 41 34" src="https://user-images.githubusercontent.com/22770576/125919467-7074b6f3-70d8-43cd-aed3-17061d5bd929.png">

**Comment by nimmneun** [comment]
You would have to add at least 1 row e.g. with an empty string as the column like so:

```
$writer = new OneSheet\Writer();
$writer->addRow(['']);
$onesheet->writeToFile('hello_world.xlsx');
```
