### ISSUE TITLE
Linking/importing xlsx file with Access show a blank screen

### ISSUE THREAD

**Issue by lkppo** [nimmneun/onesheet#68]
Hello,

I try to import/link an XLSX file in Access 2013 made with onesheet. At the very first step of the wizard the content of the XLSX file is not displayed. I think Access is puzzled by the structure of the file. Could that be fixed?

Regards,

![linking_xlsx_access_1](https://user-images.githubusercontent.com/10128284/230582532-66330103-df5f-4686-8f89-b91e362e1857.png)
![linking_xlsx_access_2](https://user-images.githubusercontent.com/10128284/230582537-f78302c0-0306-4fad-9aeb-1ae0b06e8a55.png)
![linking_xlsx_access_3](https://user-images.githubusercontent.com/10128284/230582540-a8982d22-d795-42b0-9639-a513c7164beb.png)

**Comment by nimmneun** [comment]
Hi @lkppo,

I was able to reproduce and in fix the issue (using Access 2016). If you have the ability, please try and see if the fix in the linked branch works for your version as well. I think it should.

Kind regards =)

**Comment by lkppo** [comment]
Hi @nimmneun,

This is an error I encountered at work. I will test Monday.

I have to apply the code of PR 68 on master?

Regards,

**Comment by nimmneun** [comment]
Hi @lkppo, either this - or you can just git clone the project, checkout the branch with the fix and create a simple file to test it.

**Comment by lkppo** [comment]
Hi @nimmneun,

I confirm that it works. Now Access is moaning about the version of the XLSX file being newer than the Access version but that's another problem.

Regards,
