### ISSUE TITLE
[Feature Request] Column formats

### ISSUE THREAD

**Issue by Grldk** [nimmneun/onesheet#71]
Hi,

I like this library, would love to use it, but for us the lack of column formatting is a deal breaker unfortunately. Would you consider adding simple Column Formatting for Dates and Numbers? Or would you consider a PR adding simple Date/Number Formatting?

edit: basicly the same as this: https://github.com/nimmneun/onesheet/issues/9

**Comment by jmlaine** [comment]
For Numbers, replace "is_int" by "is_numeric" in "build" function in "CellBuilder.php". That's work for int and float, not for percent.

**Comment by nimmneun** [comment]
hi @Grldk, sorry there are currently now plans to add cell formatting. The repo is more or less in a maintenance mode only.
